var T = {
  tr:{
    title:"Kullanışlı Siteler",
    hero:function(n){ return "Elle derlenmiş <em>"+n+"</em> bağlantı. Her biri benzerlerinden nerede ayrıldığını söylüyor." },
    homeLabel:"Kullanışlı Siteler — Fihrist",
    menu:"Menü", tools:"Araçlar", langLabel:"İngilizceye geç", close:"Kapat",
    langName:"English", themeName:"Tema",
    fxHead:"Fihrist", exp:"Dışa aktar:", bookmarks:"Yer imleri (HTML)", filter:"Süz", fClear:"Temizle",
    ph:"Ara: ad, açıklama, etiket, alan adı",
    count:function(n,t){return fmtN(n)+" / "+fmtN(t)+" bağlantı"},
    empty:"Eşleşen Bağlantı Yok",
    clear:"Filtreleri Temizle",
    qLabel:"Dizinde ara", themeLabel:"Temayı değiştir", topLabel:"Yukarı çık",
    rand:"Rastgele", lang:"EN",
    by:"Ekleyen",
    rel:"Benzerleri",
    verified:function(d){ return "Son Doğrulama: " + d },
    verwarn:"(Bot Engeli — Elle Bakılmalı)",
    pickTip:"Bu alana ilk girenin gitmesi gereken yer",
    page:function(a,b){return a+" / "+b+" Sayfa"},
    prev:"Önceki", next:"Sonraki",
    sorts:{cat:"Kategoriye göre", az:"A → Z", "new":"En yeni önce"},
    sortLbl:"Sırala:", sortAria:"Sıralama", more:"devamını oku",
    sib:"Bu alandaki diğer başlıklar", allAreas:"← Tüm alanlar",
    remove:function(x){ return x+" süzgecini kaldır" },
    results:function(q,n){ return "“"+q+"” için "+n+" sonuç" },
    didYouMean:"Bunu mu demek istedin:", scArea:"Alan", scCat:"Başlık",
    relevance:"Alakaya göre",
    all:"Tüm bağlantılar",
    foot:'Bağlantılar elle derlendi, son kontrol <b>'+CHECKED+'</b>. '+
         'Açıklamalar projelerin kendi belgelerine bakılarak yazıldı; karşılaştırmalı yargılar derleyene ait. '+
         'Ölü ya da hatalı bir kayıt görürsen <a href="'+REPO+'/issues/new/choose">bildir</a> — '+
         'yeni bağlantı önerileri de aynı yerden. '+
         '<a href="k/tesekkur.html">Katkıda bulunanlar</a> · '+
         'dizinin <a href="k/index.html">metin hâli</a> de var.',
    skip:"İçeriğe Atla",
    fxNote:function(f,c){ return f+" alan, "+c+" başlık" },
    hStart:"Buradan Başla", hAll:"Tümünü tek listede gör →",
    srcLess:"− Kaynakları gizle",
    srcShow:function(n){ return n+" kaynağı göster" },
    fShow:function(n){ return n+" bağlantıyı göster" },
    listsHead:"Listeler & Koleksiyonlar",
    backCat:"← Bu başlıktaki diğer kayıtlar", permaTip:"Bu kayda bağlantı", perma:"bağlantı",
    recent:"Son Eklenenler", recentLead:function(n){ return "Dizine en son giren "+n+" kayıt, aya göre." },
    dead:"Ölü", deadTip:"Son taramada yanıt vermedi — arşivden bak",
    repo:{'arşiv':"Depo Arşivlenmiş", 'bayat':"Depo Durgun", 'yok':"Depo Silinmiş"},
    repoTip:{
      'arşiv':"Kaynak deposu salt okunur; bakım durmuş. Sayfa açılıyor olabilir.",
      'bayat':function(d){ return "Depoya iki yıldan uzun süredir itme yok" +
                                  (d ? " (son: " + d + ")" : "") },
      'yok':"Kaynak deposu silinmiş"
    },
    arch:"arşiv", archTip:"Sayfanın Wayback Machine'deki kopyası",
    add:"Bağlantı Gönder",
    sTitle:"Bağlantı Gönder",
    sTab1:"Tek Bağlantı", sTab2:"Dosyadan Toplu",
    sNote:"Gönderdiğin şey <b>GitHub issue’su olarak açılır</b>, siteye kendiliğinden düşmez. "+
          'Derleyen bakar, açıklamayı yazar, uygun bulursa bir sonraki derlemede girer.',
    sNoteB:'Dosya <b>tarayıcında okunur</b>, hiçbir yere yüklenmez. '+
           'Dizinde zaten olanlar ayıklanır, geriye yalnızca yeni olanlar kalır.',
    lName:"İsim", lCat:"Kategori",
    lWhat:"Ne İşe Yarıyor?", lDiff:"Benzerlerinden Farkı Ne?",
    phWhat:"Bir iki cümle. Pazarlama metni değil, ne yaptığı.",
    phDiff:"Aynı işi yapan başka bir şeye karşı neden bu? Bilmiyorsan “bilmiyorum” yaz.",
    catAsk:"Emin Değilim",
    dupWarn:function(n){ return "Bu bağlantı dizinde zaten var: " + n },
    needUrl:"Önce bir URL yaz.",
    drop:'Yer imi dosyanı buraya sürükle ya da <u>seçmek için tıkla</u><br><code>.html · .json · .csv</code>',
    stat:function(a,b,c){ return "Okunan: "+a+" · Zaten Dizinde: "+b+" · Yeni: "+c },
    noneNew:"Yeni bağlantı çıkmadı — hepsi dizinde zaten var.",
    badFile:"Dosya okunamadı. Yer imi dışa aktarımı (.html), JSON ya da CSV bekleniyor.",
    tooBig:function(n){ return n+" bağlantı issue adresine sığmaz. Dosyayı indir, issue'ya ekle." },
    bIssue:"GitHub'da Aç", bCopy:"Kopyala", bJson:"JSON İndir", bCsv:"CSV İndir",
    copied:"Kopyalandı",
    kb:'<kbd>/</kbd> Ara · <kbd>r</kbd> Rastgele · <kbd>Esc</kbd> Temizle'
  },
  en:{
    title:"Useful Sites",
    hero:function(n){ return "<em>"+n+"</em> links, picked by hand. Each one says where it parts ways with its neighbours." },
    homeLabel:"Useful Sites — Index",
    menu:"Menu", tools:"Tools", langLabel:"Switch to Turkish", close:"Close",
    langName:"Türkçe", themeName:"Theme",
    fxHead:"Index", exp:"Export:", bookmarks:"Bookmarks (HTML)", filter:"Filter", fClear:"Clear",
    ph:"Search: name, notes, tag, domain",
    count:function(n,t){return fmtN(n)+" / "+fmtN(t)+" links"},
    empty:"No Matching Links",
    clear:"Clear Filters",
    qLabel:"Search the directory", themeLabel:"Toggle theme", topLabel:"Back to top",
    rand:"Random", lang:"TR",
    by:"Added By",
    rel:"Similar",
    verified:function(d){ return "Last Verified: " + d },
    verwarn:"(Bot-Blocked — Needs A Manual Look)",
    pickTip:"Where to go first in this area",
    page:function(a,b){return "Page "+a+" / "+b},
    prev:"Prev", next:"Next"      ,
    sorts:{cat:"By category", az:"A → Z", "new":"Newest first"},
    sortLbl:"Sort:", sortAria:"Sort order", more:"read more",
    sib:"Other headings in this area", allAreas:"← All areas",
    remove:function(x){ return "Remove filter: "+x },
    results:function(q,n){ return n+" results for “"+q+"”" },
    didYouMean:"Did you mean:", scArea:"Area", scCat:"Heading",
    relevance:"By relevance",
    all:"All links",
    foot:'Curated by hand, last checked <b>'+CHECKED+'</b>. '+
         "Descriptions are written from each project's own documentation; comparative judgements are the curator's. "+
         'Spotted a dead or wrong entry? <a href="'+REPO+'/issues/new/choose">Tell me</a> — '+
         'link suggestions go to the same place. '+
         '<a href="k/en/credits.html">Contributors</a> · '+
         'there is a <a href="k/en/index.html">plain-text edition</a> too.',
    skip:"Skip To Content",
    fxNote:function(f,c){ return f+" areas, "+c+" headings" },
    hStart:"Start Here", hAll:"See everything in one list →",
    srcLess:"− Hide sources",
    srcShow:function(n){ return "Show "+n+" sources" },
    fShow:function(n){ return "Show "+n+" links" },
    listsHead:"Lists & Collections",
    backCat:"← Other entries under this heading", permaTip:"Link to this entry", perma:"link",
    recent:"Recently Added", recentLead:function(n){ return "The "+n+" newest entries, by month." },
    dead:"Dead", deadTip:"No response in the last scan — try the archive",
    repo:{'arşiv':"Repo Archived", 'bayat':"Repo Dormant", 'yok':"Repo Deleted"},
    repoTip:{
      'arşiv':"The source repository is read-only; maintenance has stopped. The page may still load.",
      'bayat':function(d){ return "No pushes to the repository in over two years" +
                                  (d ? " (last: " + d + ")" : "") },
      'yok':"The source repository has been deleted"
    },
    arch:"archive", archTip:"The page as kept by the Wayback Machine",
    add:"Submit a Link",
    sTitle:"Submit a Link",
    sTab1:"Single Link", sTab2:"Bulk From File",
    sNote:'What you send <b>opens as a GitHub issue</b>; it does not appear on the site by itself. '+
          'The curator reads it, writes the description, and it goes in on the next build if it fits.',
    sNoteB:'The file is <b>read in your browser</b> and uploaded nowhere. '+
           'Anything already in the directory is filtered out, leaving only what is new.',
    lName:"Name", lCat:"Category",
    lWhat:"What Does It Do?", lDiff:"How Does It Differ?",
    phWhat:"A sentence or two. Not marketing copy — what it does.",
    phDiff:"Why this over something else doing the same job? If you don't know, write so.",
    catAsk:"Not Sure",
    dupWarn:function(n){ return "Already in the directory: " + n },
    needUrl:"Enter a URL first.",
    drop:'Drop your bookmark file here, or <u>click to choose one</u><br><code>.html · .json · .csv</code>',
    stat:function(a,b,c){ return "Read: "+a+" · Already Here: "+b+" · New: "+c },
    noneNew:"Nothing new — every one of these is already in the directory.",
    badFile:"Could not read the file. Expecting a bookmark export (.html), JSON or CSV.",
    tooBig:function(n){ return n+" links will not fit in an issue URL. Download the file and attach it." },
    bIssue:"Open On GitHub", bCopy:"Copy", bJson:"Download JSON", bCsv:"Download CSV",
    copied:"Copied",
    kb:'<kbd>/</kbd> Search · <kbd>r</kbd> Random · <kbd>Esc</kbd> Clear'
  }
};

